/* Pure algorithms, also exposed to Node for verification. UTC dates, annual isolation. */
const NDVI = (() => {
const DAY=86400000, names=['正常水稻','疑似其他作物','疑似撂荒地','疑似未种植','数据不足','撂荒地（确认）'];
const defaults={T1:.5,T2:.35,T3:.42,T4:.6,T5:.42,P1:180,P2:260,peak:true,interval:10,window:5,startMonth:4,endMonth:10,confirm:false};
function date(s){const m=String(s).trim().match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})(?:[T ].*)?$/);if(!m)return NaN;const t=Date.UTC(+m[1],+m[2]-1,+m[3]),d=new Date(t);return d.getUTCFullYear()==+m[1]&&d.getUTCMonth()==+m[2]-1&&d.getUTCDate()==+m[3]?t:NaN;}
function csv(text){text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||!cell)quoted=!quoted;else cell+=c;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV 引号未闭合');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function parse(text){const rows=csv(text);if(!rows.length)throw Error('CSV 为空');const header=rows.shift().map(s=>s.toLowerCase().replace(/\s/g,''));for(const k of ['plot_id','date','ndvi'])if(!header.includes(k))throw Error('缺少必需列：'+k);if(new Set(header).size!==header.length)throw Error('存在重复列名');const ix=k=>header.indexOf(k);let invalid=0,missing=0;const groups=new Map();for(const r of rows){const id=(r[ix('plot_id')]||'').trim(),t=date(r[ix('date')]);if(!id||!Number.isFinite(t)){invalid++;continue;}const year=new Date(t).getUTCFullYear(),key=JSON.stringify([id,year]);if(!groups.has(key))groups.set(key,{key,id,year,raw:[]});let str=(r[ix('ndvi')]||'').trim(),v=str===''?NaN:Number(str);if(!Number.isFinite(v)||v < -1||v>1){v=null;missing++;}groups.get(key).raw.push({t,v});}return {groups:[...groups.values()],records:rows.length,invalid,missing};}
function quantile(values,p){const a=[...values].sort((a,b)=>a-b),i=(a.length-1)*p,l=Math.floor(i);return a[l]+(a[Math.ceil(i)]-a[l])*(i-l);}
function interpolate(points,grid){let j=0;return grid.map(t=>{while(j+1<points.length&&points[j+1].t<t)j++;if(t<points[0].t||t>points.at(-1).t)return null;const a=points[j],b=points[Math.min(j+1,points.length-1)];return a.t===b.t?a.v:a.v+(b.v-a.v)*(t-a.t)/(b.t-a.t);});}
function solve(a,b){a=a.map((r,i)=>[...r,b[i]]);for(let i=0;i<b.length;i++){let p=i;for(let j=i+1;j<b.length;j++)if(Math.abs(a[j][i])>Math.abs(a[p][i]))p=j;[a[i],a[p]]=[a[p],a[i]];const v=a[i][i];if(Math.abs(v)<1e-12)return null;for(let k=i;k<=b.length;k++)a[i][k]/=v;for(let j=0;j<b.length;j++)if(j!==i){const q=a[j][i];for(let k=i;k<=b.length;k++)a[j][k]-=q*a[i][k];}}return a.map(r=>r.at(-1));}
function smooth(values,window){const n=values.length;if(n<5)return [...values];let w=Math.min(window,n%2?n:n-1);if(w<5)return [...values];return values.map((_,i)=>{const start=Math.max(0,Math.min(i-(w-1)/2,n-w));let a=Array.from({length:3},()=>[0,0,0]),b=[0,0,0];for(let j=start;j<start+w;j++){const x=j-i,v=[1,x,x*x];for(let r=0;r<3;r++){b[r]+=v[r]*values[j];for(let c=0;c<3;c++)a[r][c]+=v[r]*v[c];}}return solve(a,b)?.[0]??values[i];});}
function season(t,c){const m=new Date(t).getUTCMonth()+1;return c.startMonth<=c.endMonth?m>=c.startMonth&&m<=c.endMonth:m>=c.startMonth||m<=c.endMonth;}
function preprocess(group,c){const buckets=new Map();for(const p of group.raw)if(p.v!==null){if(!buckets.has(p.t))buckets.set(p.t,[]);buckets.get(p.t).push(p.v);}const points=[...buckets].map(([t,a])=>({t,v:a.reduce((s,v)=>s+v,0)/a.length})).sort((a,b)=>a.t-b.t);if(!points.length)return null;const grid=[];for(let t=Date.UTC(group.year,0,1);t<Date.UTC(group.year+1,0,1);t+=c.interval*DAY)grid.push(t);const values=interpolate(points,grid),indices=values.map((v,i)=>v===null?-1:i).filter(i=>i>=0),sm=smooth(indices.map(i=>values[i]),c.window),curve=grid.map((t,i)=>({t,v:null}));indices.forEach((i,j)=>curve[i].v=sm[j]);const gs=curve.filter(p=>p.v!==null&&season(p.t,c)),observedGs=points.filter(p=>season(p.t,c));let metrics={ndviMax:null,ndviAmp:null,ndviMeanGs:null,peakDoy:null};if(gs.length){const max=Math.max(...gs.map(p=>p.v)),peak=gs.find(p=>p.v===max);metrics={ndviMax:max,ndviAmp:quantile(gs.map(p=>p.v),.95)-quantile(gs.map(p=>p.v),.05),ndviMeanGs:gs.reduce((s,p)=>s+p.v,0)/gs.length,peakDoy:Math.round((peak.t-Date.UTC(group.year,0,1))/DAY)+1};}return {...group,...metrics,points,curve,insufficient:points.length<5||!gs.length||!observedGs.length};}
function classify(r,c){if(r.insufficient)return 5;if(r.ndviMax<c.T1||r.ndviMeanGs<c.T2)return 4;if(r.ndviAmp<c.T3)return 3;if(r.ndviMax>=c.T4&&r.ndviAmp>=c.T5&&(!c.peak||(r.peakDoy>=c.P1&&r.peakDoy<=c.P2)))return 1;return 2;}
function classifyAll(rows,c){const out=rows.map(r=>({...r,classCode:classify(r,c)}));if(c.confirm){const by=new Map();out.forEach(r=>{if(!by.has(r.id))by.set(r.id,[]);by.get(r.id).push(r);});for(const a of by.values()){a.sort((a,b)=>a.year-b.year);let run=[];const flush=()=>{if(run.length>=2)run.forEach(r=>r.classCode=6);run=[];};for(const r of a){if(r.provisional || r.year>=new Date().getUTCFullYear() || ![3,4].includes(r.classCode)){flush();continue;}if(run.length&&r.year!==run.at(-1).year+1)flush();run.push(r);}flush();}}return out.map(r=>({...r,className:names[r.classCode-1]}));}
function validate(c){const out={...defaults};for(const k of Object.keys(defaults)){if(typeof defaults[k]==='boolean'){out[k]=typeof c[k]==='boolean'?c[k]:defaults[k];continue;}const n=Number(c[k]),range=k.startsWith('T')?(k==='T3'||k==='T5'?[0,2]:[-1,1]):k.startsWith('P')?[1,366]:k==='interval'?[1,60]:k==='window'?[5,31]:[1,12];out[k]=Number.isFinite(n)&&n>=range[0]&&n<=range[1]?n:defaults[k];if(!k.startsWith('T'))out[k]=Math.round(out[k]);}if(out.window%2===0)out.window++;if(out.P1>out.P2){out.P1=defaults.P1;out.P2=defaults.P2;}return out;}
function example(){let rows=['plot_id,date,NDVI,valid_pixels,NDVI_std'];for(let i=0;i<20;i++)for(const year of [2023,2024])for(let day=1;day<=361;day+=10){let v;const type=i%5;if(type===0)v=.15+.72*Math.exp(-(((day-220)/47)**2));if(type===1)v=.24+.65*Math.exp(-(((day-140)/55)**2));if(type===2)v=.58+.045*Math.sin(day/40+i);if(type===3)v=.18+.03*Math.sin(day/30);if(type===4&&day>31)continue;if(type===4)v=.5;const t=new Date(Date.UTC(year,0,day)).toISOString().slice(0,10);rows.push([`P${String(i+1).padStart(3,'0')}`,t,day===111?'':v.toFixed(5),30,.04].join(','));}return rows.join('\r\n');}
return {DAY,names,defaults,date,csv,parse,quantile,interpolate,smooth,season,preprocess,classify,classifyAll,validate,example};
})();
if(typeof module!=='undefined')module.exports=NDVI;
